Manage pre-commit with Poetry in GitHub Actions
br3ndonland/inboard@84b25bc

pre-commit runs mypy from an isolated virtualenv, so it requires a
duplicate list of Python requirements. Furthermore, these requirements
are installed by pip, which reduces compatibility with Poetry. Editable
installs require a setup.py, which is not present in Poetry projects.
The following error is seen:

```text
❯ pip install -e .

ERROR: File "setup.py" not found. Directory cannot be installed in
editable mode (A "pyproject.toml" file was found, but editable mode
currently requires a setup.py based build.)
```

The simplest solution is to use `language: system`, which means
"you have to rely on whatever state the user's machine is in." This just
means the GitHub Actions workflow needs to run a Poetry install first.