Upgrade GitHub actions version
Commit 75139c73 failed the GitHub pre-commit workflow action:
https://github.com/br3ndonland/template-python/runs/468428461

The error seemed to have something to do with Python versions:

```
An unexpected error has occurred: CalledProcessError: command: \
('/opt/hostedtoolcache/Python/3.8.1/x64/bin/python', '-mvirtualenv', \
'/home/runner/.cache/pre-commit/repojxyksam8/py_env-python3.7', \
'-p', 'python3.7')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of
    python_spec='python3.7'

stderr: (none)
Check the log at /home/runner/.cache/pre-commit/pre-commit.log
[error]
The process '/opt/hostedtoolcache/Python/3.8.1/x64/bin/pre-commit'
failed with exit code 1
```